# -*- coding: utf-8 -*-
"""Speech training agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OrHmuGBMxVekENNkRiQLLb94qZPbc3p4
"""


import torch # type: ignore
from transformers import BertTokenizer, BertModel # type: ignore
import torch.nn as nn # type: ignore
from transformers import Wav2Vec2Model, Wav2Vec2FeatureExtractor # type: ignore




# Configuring BERT model to my choice using a python class
class BERTClassifier(nn.Module):
  def __init__(self, n_classes):
    super(BERTClassifier, self).__init__()

    self.bert = BertModel.from_pretrained('bert-base-uncased')

    self.drop = nn.Dropout(p=0.3)

    self.dim_reduction = nn.Linear (768,32)

    self.activation = nn.ReLU()

    # Defining the final classifier
    self.classifier = nn.Linear (32,n_classes)

  def forward(self, input_ids, attention_mask):
        # Feeding tokenized text into BERT
        outputs = self.bert(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

        pooled_outputs = outputs.pooler_output
        output = self.drop(pooled_outputs)

        reduced = self.dim_reduction(output)
        reduced = self.activation(reduced)

        # Making the final prediction
        return self.classifier(reduced)




# Building a class for audio processing, using a variant of wav2vec2 speciic for 4 emotion classification
class Wav2Model (nn.Module):
  def __init__(self):
    super(Wav2Model, self).__init__()

    # Initialising the model with the pretrained weights
    self.wav2vec2 = Wav2Vec2Model.from_pretrained("superb/wav2vec2-base-superb-er")

    for param in self.wav2vec2.parameters():
      param.requires_grad = False

    # Unfreezing final 2 layers
    for l in self.wav2vec2.encoder.layers[-2:]:
      for param in l.parameters():
        param.requires_grad = True


    self.dim_reduction = nn.Linear(768, 32)

    self.activation = nn.ReLU()

  def forward(self, input_values):
    # With torch.no_grad because I will not be adjusting the gradients
    outputs = self.wav2vec2(input_values)
    pooled_outputs = outputs.last_hidden_state.mean(dim=1)

    output = self.dim_reduction(pooled_outputs)
    output = self.activation(output)
    return output


class FusionModel(nn.Module):
  def __init__(self, wav_model, model, num_classes=4):
      super(FusionModel, self).__init__()
      self.WavModel = wav_model
      self.BertModel = model

      self.drop = nn.Dropout(p=0.3)

      self.classifier = nn.Linear(64, num_classes)

  def forward(self, input_values, input_ids, attention_mask):
      outputs_bert = self.BertModel.bert(
          input_ids=input_ids,
          attention_mask=attention_mask
      )
      pooled_bert = outputs_bert.pooler_output
      reduced_bert = self.BertModel.drop(pooled_bert)
      reduced_bert = self.BertModel.dim_reduction(reduced_bert)
      reduced_bert = self.BertModel.activation(reduced_bert)

      reduced_wav = self.WavModel(input_values)

      concat_outputs = torch.cat((reduced_bert, reduced_wav), dim=1)
      concat_outputs = self.drop(concat_outputs)

      return self.classifier(concat_outputs)

